### ------------------------------------------------------------------------------------------------
##  @filename  .travis.yml
##  @author  brikcss  <https://github.com/brikcss>
##  @description  https://docs.travis-ci.com/user/customizing-the-build/
### ------------------------------------------------------------------------------------------------

language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email:
    on_failure: always
env: NODE_ENV=test

node_js: '8'
before_script: npm prune -d
script: npm run test -d
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm version minor -d
    - npm publish -d
  # script:
  #   - npx semantic-release

branches:
  only:
    - master
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
